# Modified from: https://github.com/peterkappus/selenium-cucumber-docker

# run either
#   docker-compose up -d
#   docker-compose exec ruby bash
# or run
#   docker-compose --service-ports run ruby bash
# to check what the website's 
#   http://localhost:7900/?autoconnect=1&resize=scale&password=secret

version: '3'
services:
  browser:
    
    # use for Apple Silicon
    # image: seleniarm/standalone-chromium
    # image: seleniarm/standalone-firefox
    
    # image: selenium/standalone-firefox:110.0
    image: selenium/standalone-firefox
    # image: selenium/standalone-chrome
    
    ports:
      - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access
      # to access vnc through web http://localhost:7900/?autoconnect=1&resize=scale&password=secret
      - "7900:7900" #for web VNC access

  ruby:
    build: .
    volumes:
      - ..:/home/match-my-fashion-public-CodeCreators
    depends_on: 
      - browser
    environment: 
      - SELENIUM_HOST=browser
      - SELENIUM_PORT=4444
      - RAILS_HOST=ruby
      - RAILS_PORT=3000
    ports:
      - "8080:3000"
      - "3001:22"
    # command: sudo service postgresql start
